### ISSUE TITLE
无法添加ArcGISTiledMapServiceLayer和自定义basemap

### ISSUE THREAD

**Issue by wxia5** [guzhongren/ChartOnMap#2]
添加echarts的柱状图后，无法添加ArcGISTiledMapServiceLayer，也不能自定义basemap后添加到map, 但是添加ArcGISDynamicMapServiceLayer正常。是我这里的问题吗？

**Comment by guzhongren** [comment]
不应该，我这边前几天还在用是正常的，如有必要，粘贴代码

**Comment by wxia5** [comment]
感谢回复，已解决，是我js引用切片图层的问题。
