### ISSUE TITLE
Uncaught TypeError: t.className.match is not a function

### ISSUE THREAD

**Issue by Arther1228** [guzhongren/ChartOnMap#3]
显示了柱状图之后，后台会显示这个错误，而且移动地图的时候，感觉挺慢的，不知道是不是这个问题引起的，这个问题你可遇到过~ 下面是详细的错误：

echarts-all.js:7 Uncaught TypeError: t.className.match is not a function
    at p (echarts-all.js:7)
    at u.mouseout (echarts-all.js:8)
    at HTMLDivElement.<anonymous> (echarts-all.js:7)

**Comment by guzhongren** [comment]
这份代码已经不更新了，我之前做过一个直接摒弃ags api 的infoTemplate,将地理坐标转换为屏幕坐标后，将其提供给Echarts的坐标，但是只有部分图可以用，使用这个网址[Echats Pie](http://echarts.baidu.com/echarts2/doc/example/pie1.html), 数据用这个
```
option = {
    title : {
        text: '某站点用户访问来源',
        subtext: '纯属虚构',
        x:'center'
    },
    tooltip : {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c} ({d}%)"
    },
    legend: {
        orient : 'vertical',
        x : 'left',
        data:['直接访问','邮件营销','联盟广告','视频广告','搜索引擎']
    },
    toolbox: {
        show : true,
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            magicType : {
                show: true, 
                type: ['pie', 'funnel'],
                option: {
                    funnel: {
                        x: '25%',
                        width: '50%',
                        funnelAlign: 'left',
                        max: 1548
                    }
                }
            },
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,
    series : [
        {
            name:'访问来源',
            type:'pie',
            radius : '55%',
            center: ['5px', '60%'],  // 更改屏幕坐标
            data:[
                {value:335, name:'直接访问'},
                {value:310, name:'邮件营销'},
                {value:234, name:'联盟广告'},
                {value:135, name:'视频广告'},
                {value:1548, name:'搜索引擎'}
            ]
        }
    ]
};              
```
options中的center参数修改即可更改位置，将图表嵌入到地图中是dom插入的，比如append到mapId那个层级

**Comment by Arther1228** [comment]
好的，我到时候试试，暂时先用你这个代码试试，上面那个错误我在网上找到答案了，是echarts的bug，在echart-all.js的 6711行左右开始，增加一个判断：
  p = function(e) {
            if (window.G_vmlCanvasManager) return ! 0;
            e = e || window.event;
            var t = e.toElement || e.relatedTarget || e.srcElement || e.target;
			 **if (t.nodeName.toLowerCase() !== 'canvas' && t.nodeName.toLowerCase() !== 'div') {
				 return null;
			}**
            return t && t.className.match(o.elementClassName)
        },
就可以了。

**Comment by guzhongren** [comment]
66666666666
